name: Create Release

on:
  pull_request:
    branches:
      - main
    types: [closed]

env:
  RELEASE_VERSION: ${{ github.ref }}
  PR_DESCRIPTION: ${{ github.ref }}

jobs:
  release:
    name: Create Release
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Extract version from branch name (for release branches)
        if: startsWith(github.event.pull_request.head.ref, 'release/')
        run: |
          BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
          VERSION=${BRANCH_NAME#release/}
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "PR_DESCRIPTION<<$EOF" >> "$GITHUB_ENV"
          echo '${{ github.event.pull_request.body }}'>> "$GITHUB_ENV"
          echo "$EOF" >> "$GITHUB_ENV"

          echo "RELEASE_VERSION=$VERSION" >> $GITHUB_ENV

      - name: check vars
        run: |
          echo '${{ env.PR_DESCRIPTION }}'

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          release_name: "${{ env.RELEASE_VERSION }}"
          body: ${{ env.PR_DESCRIPTION }}
          draft: false
          prerelease: false
