name: Manual PROD deploy

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Say Hello      
      run: |
        echo "hello!"